# Generated by Django 4.0.3 on 2022-03-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_applied', models.DateTimeField(auto_now_add=True, verbose_name='date_applied')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('profile_picture', models.ImageField(null=True, upload_to='application/%Y/%m/%d/')),
                ('designation', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('link', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='blogs/%Y/%m/%d/')),
                ('author', models.CharField(max_length=50)),
                ('date_published', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('subject', models.TextField(max_length=300)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=150)),
                ('date_of_event', models.DateField()),
                ('description', models.TextField(max_length=150)),
                ('link', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='events/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('link', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='posts/%Y/%m/%d/')),
            ],
        ),
    ]
